version: "3"
services:

  web1:
    image: httpd
    container_name: web1
    volumes:
      - ./FRONT_web1:/usr/local/apache2/htdocs/
    networks:
      - minharede

  web2:
    image: httpd
    container_name: web2
    volumes:
      - ./FRONT_web2:/usr/local/apache2/htdocs/
    networks:
      - minharede


  proxy:
    container_name: proxy
    image: haproxy:1.6
    volumes:
      - ./proxy-config/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
    ports:
      - 80:80
    networks:
      - minharede

networks:
  minharede:
